#!/bin/bash

if [ $# -ne 4 ]; then
	echo "Usage: compare_values file1 file2 column delta"
	return 1
fi

diff -y --suppress-common-lines $1 $2 | awk -v column=$3 -v delta=$4 '
function abs(x) {
	return (x < 0 ? -x : x);
}
{
	split($0, array, "|");
	split(array[1], left, " ");
	val1 = left[column];
	split(array[2], right, " ");
	val2 = right[column];

	if (abs(val2 - val1) > delta)
		print $0;
}
'
